### ISSUE TITLE
/n inside bold breaks the bold

### ISSUE THREAD

**Issue by zerostatic-review** [quantizor/markdown-to-jsx#449]
Example markdown: "\*\*Some bold text with\n new line\*\*"

This will display as "**Some bold text with new line" (showing the asterisks)

**Comment by janpe** [comment]
@probablyup any thoughts on this? I ran into the same issue with italics.

**Comment by janpe** [comment]
There also seems to be some inconsistencies.

```
_hello 
world_
```
results in:
```
_hello world_
```

but
```
__hello 
world__
```
results in:
```
__hello world
```

**Comment by henry132109** [comment]
`*`s and `_`s are very common in mathematics. Is there a way to turn this off?

**Comment by quantizor** [comment]
> `*`s and `_`s are very common in mathematics. Is there a way to turn this off?

I would recommend using code blocks for things that contain markdown-like syntax.

**Comment by henry132109** [comment]
> > `*`s and `_`s are very common in mathematics. Is there a way to turn this off?
> 
> I would recommend using code blocks for things that contain markdown-like syntax.

you're right
