### ISSUE TITLE
Markdown not working with tailwind in Next JS 13 - example project repo added

### ISSUE THREAD

**Issue by minifisk** [quantizor/markdown-to-jsx#519]
I want to show an article with all the styles from markdown-to-jsx but can't get it to work in NextJS when using tailwind. The styles are only applied if I add it to the tailwind.css file, but it don't seem like I'm getting the styles from the project?

I've added a repo where I've reproduced this, maybe you can take a look:
https://github.com/minifisk/markdown-tailwind

**Comment by OmarAfet** [comment]
Same problem here. with tailwindcss the package won't work.

**Comment by alfianyusufabdullah** [comment]
Hi @minifisk , Have you ever tried https://tailwindcss.com/docs/typography-plugin?

**Comment by quantizor** [comment]
Same comment from the other issue, ensure your md files are being scanned by the tailwind engine so it can detect class usage if the classes are in the MD files themselves
