### ISSUE TITLE
Bug: Component's name that's a prefix of another can't be nested

### ISSUE THREAD

**Issue by desiprisg** [quantizor/markdown-to-jsx#530]
Noticed this while implementing an `<Accordion />`. I've added overrides for `<Accordion />` and `<AccordionItem />` and it seems that when nesting these, the outside element is not placed correctly.

Simplified example:
```
overrides: {
     Accordion: ({ children }) => children,
     AccordionItem: ({ children }) => children,
}
```
will yield:
![image](https://github.com/quantizor/markdown-to-jsx/assets/73396808/65c51556-ee09-4631-9ace-baadd64990c2)

If `Accordion` was not a prefix of `AccordionItem`, this would work as expected.

**Comment by alfianyusufabdullah** [comment]
Hi @desiprisg , I think you should adjust the indentation of the components you've added. Here is an example with the same case that I've already created.

![image](https://github.com/quantizor/markdown-to-jsx/assets/22283409/88ba7d75-9148-4160-a9c0-bc4253e7aa66)

**Comment by desiprisg** [comment]
@alfianyusufabdullah The issue appears when the nested component has a different name (prefixed by the first component's name). Try naming the second one `CalloutSubmission2`.
