### ISSUE TITLE
[FEAT] Add support for GFM Alerts

### ISSUE THREAD

**Issue by DerGoogler** [quantizor/markdown-to-jsx#532]
Could you add support for GFM Alerts?

Ref: https://github.com/orgs/community/discussions/16925

**Comment by quantizor** [comment]
How would you expect it to be implemented, putting the alert type in an `<em>` at the top of the `<blockquote>` or something? The library is intentionally un-opinionated about styles.

**Comment by quantizor** [comment]
With the new v7.4 [`renderRule` option](https://github.com/quantizor/markdown-to-jsx?tab=readme-ov-file#optionsrenderrule) you can implement this yourself if desired by inspecting `node.children` for an appropriate first text child.

**Comment by DerGoogler** [comment]
This option is awesome 👍

**Comment by robertotcestari** [comment]
Hello @DerGoogler did you implement this? Do you have an example code?  

thanks!

**Comment by DerGoogler** [comment]
@quantizor To add alerts like GitHub... isn't posible here ....

it returns something like this here:
```json
[
  {
    "text": "[",
    "type": "27"
  },
  {
    "text": "!CAUTION",
    "type": "27"
  },
  {
    "text": "]\nNegative ",
    "type": "27"
  },
  {
    "text": "potential",
    "type": "5"
  },
  {
    "text": " consequences of an action.\nNegative ",
    "type": "27"
  },
  {
    "text": "potential",
    "type": "5"
  },
  {
    "text": " consequences of an action.",
    "type": "27"
  }
]
```

how I should parse such things?????
