### ISSUE TITLE
Custom override closing tags rendered in Firefox

### ISSUE THREAD

**Issue by dmaier-indeed** [quantizor/markdown-to-jsx#535]
As of the 7.4 update, custom component overrides that render children are rendering the closing tag in Firefox. This only occurs when the custom component render children; self-closing custom components render correctly. This rendered correctly in version 7.3.2

# Code to reproduce

```
<Markdown
    options={{
        overrides: {
            CustomComponent: ({ children }) => <h3>Hello {children}</h3>
        }
    }}
>
    {'This will render the closing tag <CustomComponent>Drew</CustomComponent>'}
</Markdown>
```

# Screenshots

**Firefox (the bug occurs)**

<img width="258" alt="firefox" src="https://github.com/quantizor/markdown-to-jsx/assets/68197808/2d8026ee-f158-4648-ba36-53812af5229c">

**Chrome (bug does not occur)**

<img width="252" alt="chrome" src="https://github.com/quantizor/markdown-to-jsx/assets/68197808/edcf8c80-4181-4224-8ef4-f9bcca573d04">

**Comment by stevemckenzie** [comment]
Any workarounds for this? I want to be able to use the new `renderRules` feature but I am also experiencing this issue.

**Comment by dmaier-indeed** [comment]
@stevemckenzie yes I ended up doing the same thing. Instead of nesting, make the parent tag contain the child in its render function and make it self-closing

**Comment by rodeyseijkens** [comment]
We where running into the same issue on our application.

I saw that storybook rolled back to `v7.1.8` too, this version works for us.

Tried `7.1.9` and it breaks again.

So we are sticking to `v7.1.8` for now.

**Comment by seancdavis** [comment]
I was seeing similar behavior. Resolved by downgrading to `7.3.2` (`7.4.0` was broken).

Noting that `7.1.8` and `7.1.9` also seemed to resolve my issues. (`7.1.9` was not broken for me.)

**Comment by Juanxpeke** [comment]
Had the same issue on version ```7.4.1```, downgrading to ```7.3.2``` solved my problem.

**Comment by lukeapage** [comment]
Also, just to be ultra confusing, in index.cjs run through prettier:
![image](https://github.com/quantizor/markdown-to-jsx/assets/309321/a603bfa5-8e95-41d2-a6c4-9b30cf7d15e2)

but in index.modern.js


![image](https://github.com/quantizor/markdown-to-jsx/assets/309321/8602d28f-9624-4eaa-8ae1-c96be07da94d)

It looks like the latest 7.4.1 has been published with an out of date index.cjs....

**Comment by zegl** [comment]
Hey @quantizor. I'm willing to sponsor this issue and #542 with $100 (via polar.sh) to get it fixed.

**Comment by quantizor** [comment]
> The problem was introduced in [1583486](https://github.com/quantizor/markdown-to-jsx/commit/1583486dd844b56e673d7551078b4b28e05a1b99)
> 
> specifically this change:
> 
> ![image](https://private-user-images.githubusercontent.com/309321/310881609-29ec747e-4448-4ef8-8328-5d5565ff12c4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyNTM1NzEsIm5iZiI6MTcxMDI1MzI3MSwicGF0aCI6Ii8zMDkzMjEvMzEwODgxNjA5LTI5ZWM3NDdlLTQ0NDgtNGVmOC04MzI4LTVkNTU2NWZmMTJjNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxMlQxNDIxMTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZTk1Y2NjYmU1NDQzZjRkOWRkNmViYWNlOTk1ZTFmZDExOTYxYTRiZmVhMDExM2E0ZGRlYmYxZDQwNmRhZDhkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.SBuoKk09iZnlqmiLDmbbyWw0fZvgkkxvDRM0v4Gusr4)
> 
> and adding these 3 lines seems to fix the problem:
> 
> ```
>     if (typeA < typeB) {
>       return -1;
>     }
> ```
> 
> the reason is that array sort is not stable in firefox.
> 
> There are 2 other fixes:
> 
> 1. adjust the ordering of all the rules. The problem is that self closing tag rule can end up higher in priority than the html tag rule. This causes self closing tags to be parsed first and the closing tag is then left over and parsed as text
> 2. implement a quicksort thats used instead of the native sort.
> 
> @quantizor Can you comment here on what the best fix would be and whether you want a Pr or you will take it from here?

Did you end up making a PR for this? Looks easy enough to accept.

**Comment by lukeapage** [comment]
No, I was waiting to hear the correct fix. If you want me to I can but it will be tomorrow.

**Comment by quantizor** [comment]
> Hey @quantizor. I'm willing to sponsor this issue and #542 with $100 (via polar.sh) to get it fixed.

Donations to my Github Sponsor profile are appreciated :) looking at this now

**Comment by quantizor** [comment]
Fixed in https://github.com/quantizor/markdown-to-jsx/releases/tag/v7.4.3
