### ISSUE TITLE
I want to be able to return HTML strings directly

### ISSUE THREAD

**Issue by Boboboer** [quantizor/markdown-to-jsx#537]
Sometimes I need to get the parsed HTML string directly, like a third-party library like markdown-it, so I can add some extra DOM to the HTML, such as cursor elements when streaming.
Fetching HTML strings directly does not seem to be supported at this time

**Comment by quantizor** [comment]
Correct, this library exclusively emits jsx as per the name. [`simple-markdown`](https://www.npmjs.com/package/simple-markdown) has an HTML-only mode I think but does not support all the same features.
