### ISSUE TITLE
Cannot render tag if formatted in a certain way.

### ISSUE THREAD

**Issue by Khongchai** [quantizor/markdown-to-jsx#540]
If we do this 
```ts
const string = `<p>
Item detail
<span
  style="
    color: #fddb67;
    font-size: 11px;
    font-style: normal;
    font-weight: 500;
    line-height: 18px;
    text-decoration-line: underline;
  "
  >debug item 1</span
>
</p>`;


<Markdown>{string}</Markdown>
```
This error would be thrown 
<img width="586" alt="image" src="https://github.com/quantizor/markdown-to-jsx/assets/56601823/85c85b18-2a47-4be0-8367-204a3ae04578">

But if we inline the entire string, the content is rendered correctly with no errors

```ts
const string = `<p> Item detail <span style=" color: #fddb67; font-size: 11px; font-style: normal; font-weight: 500; line-height: 18px; text-decoration-line: underline; ">debug item 1</span> </p>`;
```

Not sure why this happens, but we were using another library and it was rendering the first version just fine.

**Comment by janpe** [comment]
I wonder if this is the same as #449.

If you put your markdown in here: https://markdown-to-jsx.quantizor.dev/

The output you get is: `Item detail debug item 1</span > </p>`

**Comment by janpe** [comment]
@quantizor is this an issue you are aware about? Do you have any thoughts on it? For me it is currently something that prevents me from using the library which I would otherwise be very happy to use

**Comment by quantizor** [comment]
Hi, yes likely a case of some regexes not accounting for newlines properly. Will look into it
