### ISSUE TITLE
<blockquote> rendering is broken in Firefox after v7.4.0

### ISSUE THREAD

**Issue by zegl** [quantizor/markdown-to-jsx#542]
Hey, thanks for a fantastic library!

`blockquote` rendering seems to have broken sometime between `v7.3.2` and `v7.4.0` and is still broken on the latest release.

The bug only affects Firefox (v122), and does not affect Chrome or Safari.

This can be reproduced the demo ( https://markdown-to-jsx.quantizor.dev/ ) in Firefox:

Enter the following:

```
<blockquote>
hello
</blockquote>
```

The following is rendered:

```
<div class="sc-jTQCzO fhGuKO"><div><blockquote></blockquote><p>hello
&lt;/blockquote&gt;</p></div></div>
```

<img width="1137" alt="Screenshot 2024-02-15 at 15 13 28" src="https://github.com/quantizor/markdown-to-jsx/assets/47952/9f19c399-1acb-4b91-994d-0028c79f6095">

In other browsers the blockquote is rendered correctly.

**Comment by quantizor** [comment]
Should be fixed with https://github.com/quantizor/markdown-to-jsx/releases/tag/v7.4.3

Sorry about that!
