### ISSUE TITLE
Version 7.4.1 has a strange consol.log in index.cjs and index.umd.js - console.log("AHHHHHHHH")

### ISSUE THREAD

**Issue by devbrains-com** [quantizor/markdown-to-jsx#543]
Hi there

Why does the Version 7.4.1 has this console output in the index.js and index.umd.js? There is also another console.log that looks strange.

<img width="425" alt="image" src="https://github.com/quantizor/markdown-to-jsx/assets/38520987/e68d498b-3602-42eb-a2ff-24930227ab64">

Thanks for clarifying.

**Comment by zegl** [comment]
I've seen this too and have been wondering where it's coming from, but haven't tracked it down yet...

**Comment by quantizor** [comment]
🤦🏼‍♂️ I need to get changesets set up so I'm not releasing from my machine anymore

**Comment by quantizor** [comment]
https://github.com/quantizor/markdown-to-jsx/releases/tag/v7.4.2
