### ISSUE TITLE
Can't disable HTML sanitization

### ISSUE THREAD

**Issue by cfotos** [quantizor/markdown-to-jsx#564]
I want to be able to render an anchor tag with an onclick attribute that executes some javascript. This was possible before version 6.11.4, but was changed in [this PR](https://github.com/quantizor/markdown-to-jsx/pull/249). 

I think that users should be able to disable this sanitization. In my case, the markdown I'm rendering will always come from a trusted source, so I don't have to worry about XSS.

**Comment by quantizor** [comment]
An option to disable sanitization makes sense

**Comment by SukkaW** [comment]
I've created a PR #579 that implements this feature. @quantizor Would you like to review it?

**Comment by nitbix** [comment]
I'd be keen to see this happen as well, I have a couple of legitimate use cases where data URIs are being used in href.
