### ISSUE TITLE
Code scanning alert - Incomplete string escaping or encoding - False positive?

### ISSUE THREAD

**Issue by tjcouch-sil** [quantizor/markdown-to-jsx#608]
Hi `markdown-to-jsx` maintainers!

I have code scanning running on minified bundled code including your package. It flagged a piece of code coming from your package as "Incomplete string escaping or encoding". The code in question is in the following line:

https://github.com/quantizor/markdown-to-jsx/blob/3a04b9ed86d67a3b72c59e605aac00aa3e8f59d5/index.tsx#L1760

It doesn't like the string replacement. I imagine it probably thinks this replacement is intended to escape the string and prepare it for display; however, this replacement does not seem to be preparing the string for safely displaying.

My understanding is that this library is not written with the intention of making anything you pass into it safe to display, which makes this complicated.

I have some vague guesses regarding what's happening in this code, but I don't know enough about this package to say I can really tell what's happening here. I just wanted to present this to you and ask if you can tell more about what exactly the code alert is concerned about since you have more context around how this code is being used. Could you share with me some context regarding how this code is being used and help me to determine if there is something I need to do to account for this or if I can safely consider this a false positive?

Thank you very much for your time and consideration!

Screenshots of the code alert description:
![image](https://github.com/user-attachments/assets/f5926176-ad02-4301-9a4e-1f0c6fd3c93b)
![image](https://github.com/user-attachments/assets/21e72124-73b2-445d-88a8-50765d81450d)
Links in the screenshot:
- [OWASP Top Ten 2017 | A1:2017-Injection | OWASP Foundation](https://owasp.org/www-project-top-ten/2017/A1_2017-Injection.html)
- [sqlstring - npm](https://www.npmjs.com/package/sqlstring)
- [CWE - CWE-20: Improper Input Validation (4.15)](https://cwe.mitre.org/data/definitions/20.html)
- [CWE - CWE-80: Improper Neutralization of Script-Related HTML Tags in a Web Page (Basic XSS) (4.15)](https://cwe.mitre.org/data/definitions/80.html)
- [CWE - CWE-116: Improper Encoding or Escaping of Output (4.15)](https://cwe.mitre.org/data/definitions/116.html)

**Comment by quantizor** [comment]
Basically when using link references if the corresponding ref is not available it puts the content back into the document with the square bracket escaped so it won't get reparsed.

e.g.

```md
[Foo][1] bar
```

There should be a corresponding entry at the end of the document:

```md
[1]: https://google.com
```

But if there isn't one, then we fall back to putting the raw content back in as-is with a touch of escaping.

**Comment by quantizor** [comment]
tbh this might not even be needed, I'll look into it
