### ISSUE TITLE
Is markdown-to-jsx making URLs to anchor links?

### ISSUE THREAD

**Issue by yuis-ice** [quantizor/markdown-to-jsx#609]
If it's not my mistake, it looks markdown-to-jsx is making any URLs in the given text into an anchor `a` html tag. In Markdown, there's a markup rule for that, `[label](url)`. I'm confused if this is a bug, or feature, or because of my (Next.js/React) environment. If this is an expected behavior, how can we turn off/opt out of the feature to automatically linkify a URL?

**Comment by quantizor** [comment]
This library does automatically link detected bare URLs in markdown documents. Perhaps a configuration option would make sense for this, hasn't come up until now I think as a potential issue.
