### ISSUE TITLE
Parsing lists as strings

### ISSUE THREAD

**Issue by MichalPaszowski** [quantizor/markdown-to-jsx#611]
I would like to parse unordered lists as strings. Examples:
```
* test1 
* test2
```
should be 
```
* test1 
* test2
```
and not 
```
- test1
- test2
```

Ideas how I can achieve that?

**Comment by quantizor** [comment]
I have some upcoming functionality in the v8 refactor that should allow for customization of which rules are run. In the meantime, you can escape the asterisk or use a code block if you don't want list functionality.
