### ISSUE TITLE
Character "|" breaks links when they are part of the list or header element.

### ISSUE THREAD

**Issue by MichalPaszowski** [quantizor/markdown-to-jsx#622]
Peculiar one:
`# [test|](https://google.com)`
or
`* [test|](https://google.com)`
is not interpreted correctly, meaning link is shown "as is" in raw form `* [test|](https://google.pl/)`
outside list or header it works as intended.

**Comment by quantizor** [comment]
This might be fixed now, there was an issue with table detection

**Comment by MichalPaszowski** [comment]
I can confirm it works now, thanks ❤️
